---
title: "SOL analysis, November 21st 2023"
output: 
  html_document:
    css: Wil_style.css
    theme: default
    toc: TRUE
    toc_float: TRUE
    number_sections: TRUE
always_allow_html: yes
---

```{r setup1, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(bslib)
library(DT)
library(dplyr)
library(gglaplot)
library(ggplot2)
library(data.table)
library(tidyr)
library(stringr)
library(tidyverse)
library(plotly)
library(sf)
library(htmlwidgets)
library(knitr)
library(lubridate)
library(maps)
library(scales)
library(forcats)

data_dir <- 'DATA/'
chart_dir <- 'CHARTS/'


#devtools::load_all("Q:/Teams/D&PA/Demography/demogtools/")

#colour_palette <- gla_colour_palette()[c(3,6,2,4,5,7,1)]

# Disable scientific notation
options(scipen=999)

```


```{r setup2, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}


## Import data for the SOL V4 plots


input_totalPop <- fread(paste0(data_dir,"Fig1_populationChange.csv"))%>% 
  data.frame()
input_PopbyCOB_UKnonUK <- fread(paste0(data_dir,"Fig2_COBChange_UKnonUK.csv"))%>% 
  data.frame()
input_NonUKPop_ROB <- fread(paste0(data_dir,"Fig3_COBChange_nonUK_Region.csv"))%>% 
  data.frame()
input_totalBirths <- fread(paste0(data_dir,"Fig4_BirthsChange.csv"))%>% 
  data.frame()
input_Births_MothersUKnonUK <- fread(paste0(data_dir,"Fig5_BirthsChange_MothersUKnonUK.csv"))%>% 
  data.frame()
input_Births_MothersRegion <- fread(paste0(data_dir,"Fig6_BirthsChange_nonUK_MothersRegionOB.csv"))%>% 
  data.frame()


```



```{r fig1, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}


my_pal1 <- gla_pal(palette_type = "categorical",
                   palette_name = "core", n = 3)

totalPop_ed <- input_totalPop %>%
  mutate(Source_factor = as.factor(source)) %>%
  mutate(PopulationM = value/1000000) %>%
  data.frame()

Fig1 <- totalPop_ed %>%
  ggplot(aes(x=year, y=PopulationM, color=Source_factor, group=Source_factor, linetype = Source_factor)) + 
  scale_color_manual(values=my_pal1) +
  theme_gla(free_y_facets = TRUE) +
 # theme(axis.title.y=element_blank()) +
 # theme(axis.title.y = element_text(size = rel(0.9)))+
  geom_line(size=2) +
  scale_y_continuous(limits=c(7, 9), breaks=c(7.0, 7.5, 8.0, 8.5, 9.0), labels = c('7.0M', '7.5M', '8.0M', '8.5M', "9.0M")) +
  labs(title = "Estimated population of London 2001 to 2021",
       caption = paste0("Sources: As for chart in previous report"))
Fig1

# ggsave (filename = (paste0(chart_dir, "cohort_change_map.png")),
#          plot = cohort_change_map,
#          device = "png",
#          dpi=600,
#          width = 9,
#          height = 5.56,
#          units = "in")

```

```{r fig2, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}


my_pal1 <- gla_pal(palette_type = "categorical",
                   palette_name = "core", n = 3)

PopbyCOB_UKnonUK_ed <- input_PopbyCOB_UKnonUK %>%
  mutate(COB_factor = as.factor(cob)) %>%
  mutate(PopulationM = value/1000000) %>%
  data.frame()

Fig2 <- PopbyCOB_UKnonUK_ed %>%
  ggplot(aes(x=year, y=PopulationM, color=COB_factor, group=COB_factor)) + 
  scale_color_manual(values=my_pal1) +
  theme_gla(free_y_facets = TRUE) +
  geom_line(size=2) +
  scale_y_continuous(limits=c(0, 6), breaks=c(0, 1, 2, 3, 4, 5, 6), labels = c('0.0', '1.0M', '2.0M', '3.0M', '4.0M', '5.0M', '6.0M'))+
  labs(title = "Population of London 2001 to 2021 by whether born in UK",
       caption = paste0("Sources: As for chart in previous report"))
Fig2

# ggsave (filename = (paste0(chart_dir, "cohort_change_map.png")),
#          plot = cohort_change_map,
#          device = "png",
#          dpi=600,
#          width = 9,
#          height = 5.56,
#          units = "in")

```


```{r fig3, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

NonUKPop_ROB_ed <- input_NonUKPop_ROB %>%
  mutate(COB_factor = as.factor(cob)) %>%
  mutate(PopulationM = value/1000000) %>%
  data.frame()

my_pal1 <- gla_pal(palette_type = "categorical",
                   palette_name = "core", n = 6)

Fig3 <- NonUKPop_ROB_ed %>%
  ggplot(aes(x=year, y=PopulationM, color=COB_factor, group=COB_factor)) + 
  scale_color_manual(values=my_pal1) +
  theme_gla(free_y_facets = TRUE) +
  geom_line(size=2) +
  scale_y_continuous(limits=c(0, 1.5), breaks=c(0, 0.5, 1, 1.5), labels = c('0.0', '0.5M', '1.0M', '1.5M'))+
  labs(title = "Non-UK born population of London 2001 to 2023 by region of birth",
       caption = paste0("Sources: As for chart in previous report"))
Fig3

# ggsave (filename = (paste0(chart_dir, "cohort_change_map.png")),
#          plot = cohort_change_map,
#          device = "png",
#          dpi=600,
#          width = 9,
#          height = 5.56,
#          units = "in")


```


```{r fig4, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}


my_pal1 <- gla_pal(palette_type = "categorical",
                   palette_name = "core", n = 3)

totalBirths_ed <- input_totalBirths %>%
  mutate(Source_factor = as.factor(type)) %>%
  mutate(date = dmy(year_ending_date)) %>%
  mutate(births = as.numeric(annual_births)) %>%
  data.frame()



Fig4 <- totalBirths_ed %>%
  ggplot(aes(x=date, y=births, color=Source_factor, group=Source_factor)) + 
  scale_color_manual(values=my_pal1) +
  theme_gla(free_y_facets = TRUE) +
  geom_line(size=2) +
  scale_x_date(labels = date_format("%m-%Y"))+
  scale_y_continuous(limits=c(100, 140), breaks=c(100, 110, 120, 130, 140), labels = c('100K', '110K', '120K', '130K', '140K'))+
  labs(title = "Annual births in London 2001 to 2023",
       caption = paste0("Sources: As for chart in previous report"))
Fig4

# ggsave (filename = (paste0(chart_dir, "cohort_change_map.png")),
#          plot = cohort_change_map,
#          device = "png",
#          dpi=600,
#          width = 9,
#          height = 5.56,
#          units = "in")

```

```{r fig5, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}


my_pal1 <- gla_pal(palette_type = "categorical",
                   palette_name = "core", n = 3)

Births_MothersUKnonUK_ed <- input_Births_MothersUKnonUK %>%
  mutate(COB_factor = as.factor(mcob)) %>%
  mutate(PopulationK = value/1000) %>%
  data.frame()

Fig5 <- Births_MothersUKnonUK_ed %>%
  ggplot(aes(x=year, y=PopulationK, color=COB_factor, group=COB_factor)) + 
  scale_color_manual(values=my_pal1) +
  theme_gla(free_y_facets = TRUE) +
  geom_line(size=2) +
  scale_y_continuous(limits=c(40, 80), breaks=c(40, 50, 60, 70, 80), labels = c('40K', '50K', '60K', '70K', '80K'))+
  labs(title = "Annual births in London 2001 to 2021 by whether mother was born in UK",
       caption = paste0("Sources: As for chart in previous report"))
Fig5

# ggsave (filename = (paste0(chart_dir, "cohort_change_map.png")),
#          plot = cohort_change_map,
#          device = "png",
#          dpi=600,
#          width = 9,
#          height = 5.56,
#          units = "in")

```

```{r fig6, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

Births_MothersRegion_ed <- input_Births_MothersRegion  %>%
  mutate(COB_factor = as.factor(mcob)) %>%
  mutate(PopulationK = value/1000) %>%
  data.frame()

my_pal1 <- gla_pal(palette_type = "categorical",
                   palette_name = "core", n = 6)

Fig6 <- Births_MothersRegion_ed %>%
  ggplot(aes(x=year, y=PopulationK, color=COB_factor, group=COB_factor)) + 
  scale_color_manual(values=my_pal1) +
  theme_gla(free_y_facets = TRUE) +
  geom_line(size=2) +
  scale_y_continuous(limits=c(0, 30), breaks=c(0, 10, 20, 30), labels = c('0.0', '10K', '20K', '30K'))+
  labs(title = "Annual births in London 2001-2022 by mother's region of birth (Non UK)",
       caption = paste0("Sources: As for chart in previous report"))
Fig6

# ggsave (filename = (paste0(chart_dir, "cohort_change_map.png")),
#          plot = cohort_change_map,
#          device = "png",
#          dpi=600,
#          width = 9,
#          height = 5.56,
#          units = "in")


```
